### ISSUE TITLE
The code about ImageNet dataset?

### ISSUE THREAD

**Issue by blue-blue272** [jiawei-ren/BalancedMetaSoftmax-Classification#4]
Can you upload the code about the training of ImageNet?

Thanks!

**Comment by jiawei-ren** [comment]
The configuration files for ImageNet-LT dataset have been provided in [`config/ImageNet-LT`](https://github.com/jiawei-ren/BalancedMetaSoftmax-Classification/tree/main/config/ImageNet_LT). 

We have not tried our algorithm on the original ImageNet dataset, since ImageNet-LT has been a more popular benchmark in existing long-tailed classification works. You may change the option `dataset: ImageNet_LT` to `dataset: ImageNet` in the configuration file to use [the original ImageNet data list](https://github.com/jiawei-ren/BalancedMetaSoftmax-Classification/tree/main/data/ImageNet). Do let us know if you have any result on the original ImageNet dataset!

**Comment by jiawei-ren** [comment]
I will close the issue for now. Feel free to reopen it if you have any further questions.
